import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import type {
  ConfigSnapshot,
  ConfigSnapshotFileName,
  ConfigSnapshotInfo,
  ConfigSnapshotList,
} from "@palserver/shared";
import type { DriverContext } from "./driver.js";
import type { InstanceRecord } from "./store.js";
import { serverRoot } from "./native.js";
import { makeDirInPod, readFileInPod, writeFileInPod } from "./k8s-files.js";

/** The on-disk directory is deliberately local to one instance. */
export const CONFIG_BACKUPS_DIR = "config-backups";
export const CONFIG_SNAPSHOT_FILES = ["PalWorldSettings.ini", "Engine.ini"] as const;

const NATIVE_PLATFORM_DIR = process.platform === "win32" ? "WindowsServer" : "LinuxServer";
const NATIVE_CONFIG_DIR = ["Pal", "Saved", "Config", NATIVE_PLATFORM_DIR];
const K8S_CONFIG_DIR = "Pal/Saved/Config/LinuxServer";
const SNAPSHOT_ID = /^[a-z0-9]+-[a-f0-9]{16}$/;

type SnapshotFiles = ConfigSnapshot["files"];

export type ConfigSnapshotResult =
  | { supported: false; reason: string; snapshot?: undefined }
  | { supported: true; snapshot: ConfigSnapshotInfo };

export interface ConfigSnapshotRestoreResult {
  supported: boolean;
  reason?: string;
  snapshot?: ConfigSnapshotInfo;
  safetySnapshot?: ConfigSnapshotInfo;
}

function fail(message: string, statusCode = 400): Error & { statusCode: number } {
  return Object.assign(new Error(message), { statusCode });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(value).sort();
  return actual.length === keys.length && actual.every((key, index) => key === [...keys].sort()[index]);
}

function configBackupsDir(ctx: DriverContext): string {
  return path.join(ctx.instanceDir, CONFIG_BACKUPS_DIR);
}

/** Accept only identifiers generated by this module, never a path or filename. */
export function isSafeConfigSnapshotId(id: string): boolean {
  return SNAPSHOT_ID.test(id) && path.basename(id) === id;
}

function requireSafeSnapshotId(id: string): void {
  if (!isSafeConfigSnapshotId(id)) throw fail("快照 ID 不合法", 400);
}

/** Resolve a snapshot path only after validating the agent-generated ID. */
export function configSnapshotPath(ctx: DriverContext, id: string): string {
  requireSafeSnapshotId(id);
  return path.join(configBackupsDir(ctx), `${id}.json`);
}

function generatedSnapshotId(): string {
  return `${Date.now().toString(36)}-${crypto.randomBytes(8).toString("hex")}`;
}

function utf8Size(files: SnapshotFiles): number {
  return CONFIG_SNAPSHOT_FILES.reduce(
    (total, name) => total + (files[name] === null ? 0 : Buffer.byteLength(files[name], "utf8")),
    0,
  );
}

function invalidSnapshot(message: string): never {
  throw fail(`設定快照內容無效: ${message}`, 422);
}

/** Snapshots must preserve raw user files, including files that health checks
 * classify as corrupted. Only reject values that cannot safely be persisted. */
function validateSnapshotText(name: ConfigSnapshotFileName, text: unknown): asserts text is string | null {
  if (text === null) return;
  if (typeof text !== "string") invalidSnapshot(`${name} 必須是文字`);
  if (text.includes("\0")) invalidSnapshot(`${name} 含有 NUL 字元`);
}

/** Validate the small INI grammar before accepting or restoring a snapshot. */
export function validateConfigIni(name: ConfigSnapshotFileName, text: unknown): asserts text is string {
  if (text === null) return;
  if (typeof text !== "string") invalidSnapshot(`${name} 必須是文字`);
  if (text.includes("\0")) invalidSnapshot(`${name} 含有 NUL 字元`);

  let sawSection = false;
  let sawWorldSection = false;
  let sawOptionSettings = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === "" || line.startsWith(";") || line.startsWith("#")) continue;
    const section = /^\[([^\]]+)\]$/.exec(line);
    if (section) {
      sawSection = true;
      sawWorldSection ||= section[1] === "/Script/Pal.PalGameWorldSettings";
      continue;
    }
    if (line.startsWith("[")) invalidSnapshot(`${name} 區段標頭未正確關閉`);

    const equals = line.indexOf("=");
    if (equals <= 0 || !sawSection) invalidSnapshot(`${name} 無法解析的內容:「${line.slice(0, 40)}」`);
    const key = line.slice(0, equals).trim();
    if (!key) invalidSnapshot(`${name} 存在空白鍵名`);
    if (name === "PalWorldSettings.ini" && key === "OptionSettings") {
      const value = line.slice(equals + 1).trim();
      if (!value.startsWith("(") || !value.endsWith(")")) {
        invalidSnapshot("PalWorldSettings.ini 的 OptionSettings 括號不完整");
      }
      let depth = 0;
      for (const char of value) {
        if (char === "(") depth++;
        if (char === ")") depth--;
        if (depth < 0) invalidSnapshot("PalWorldSettings.ini 的 OptionSettings 括號不平衡");
      }
      if (depth !== 0) invalidSnapshot("PalWorldSettings.ini 的 OptionSettings 括號不平衡");
      sawOptionSettings = true;
    }
  }

  if (!sawSection) invalidSnapshot(`${name} 找不到任何區段標頭`);
  if (name === "PalWorldSettings.ini" && !sawWorldSection) {
    invalidSnapshot("PalWorldSettings.ini 缺少 PalGameWorldSettings 區段");
  }
  if (name === "PalWorldSettings.ini" && !sawOptionSettings) {
    invalidSnapshot("PalWorldSettings.ini 缺少 OptionSettings");
  }
}

function validateSnapshotPayload(value: unknown): ConfigSnapshot {
  if (!isRecord(value) || !exactKeys(value, ["files", "metadata", "reason", "createdAt", "size"])) {
    invalidSnapshot("JSON 欄位不符合固定快照格式");
  }
  if (!isRecord(value.files) || !exactKeys(value.files, CONFIG_SNAPSHOT_FILES)) {
    invalidSnapshot("只能包含 PalWorldSettings.ini 與 Engine.ini");
  }
  const files = value.files as unknown as SnapshotFiles;
  validateSnapshotText("PalWorldSettings.ini", files["PalWorldSettings.ini"]);
  validateSnapshotText("Engine.ini", files["Engine.ini"]);

  if (!isRecord(value.metadata) || !exactKeys(value.metadata, ["instanceId", "backend"])) {
    invalidSnapshot("metadata 欄位不完整");
  }
  if (typeof value.metadata.instanceId !== "string" || value.metadata.instanceId.length === 0) {
    invalidSnapshot("metadata.instanceId 不合法");
  }
  if (value.metadata.backend !== "native" && value.metadata.backend !== "k8s" && value.metadata.backend !== "docker") {
    invalidSnapshot("metadata.backend 不合法");
  }
  if (typeof value.reason !== "string" || value.reason.trim().length === 0) invalidSnapshot("reason 不可為空");
  if (typeof value.createdAt !== "string" || Number.isNaN(Date.parse(value.createdAt))) {
    invalidSnapshot("createdAt 不是有效時間");
  }
  if (typeof value.size !== "number" || !Number.isSafeInteger(value.size) || value.size !== utf8Size(files)) {
    invalidSnapshot("size 與 INI 內容不一致");
  }
  return value as unknown as ConfigSnapshot;
}

function loadSnapshot(ctx: DriverContext, id: string): ConfigSnapshotInfo {
  const file = configSnapshotPath(ctx, id);
  let payload: unknown;
  try {
    payload = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") throw fail(`找不到設定快照 ${id}`, 404);
    throw fail(`設定快照 ${id} 的 JSON 無法解析`, 422);
  }
  return { id, ...validateSnapshotPayload(payload) };
}

export function readConfigSnapshot(ctx: DriverContext, id: string): ConfigSnapshotInfo {
  return loadSnapshot(ctx, id);
}

/** docker bind-mount: ${instanceDir}/saved = Pal/Saved, so config is under saved/Config/... */
function nativeConfigFile(rec: InstanceRecord, ctx: DriverContext, name: ConfigSnapshotFileName): string {
  if (rec.backend === "docker") {
    return path.join(ctx.instanceDir, "saved", "Config", NATIVE_PLATFORM_DIR, name);
  }
  return path.join(serverRoot(rec, ctx), ...NATIVE_CONFIG_DIR, name);
}

function k8sConfigFile(name: ConfigSnapshotFileName): string {
  return `${K8S_CONFIG_DIR}/${name}`;
}

function noPod(message: string): Error & { statusCode: number } {
  return fail(`k8s 沒有運行中的 Pod，無法${message}`, 409);
}

function isNoPodError(error: unknown): boolean {
  return error instanceof Error && /找不到運行中的 game-server Pod/.test(error.message);
}

async function readConfigFiles(rec: InstanceRecord, ctx: DriverContext): Promise<SnapshotFiles> {
  if (rec.backend !== "k8s") {
    const files = {} as SnapshotFiles;
    for (const name of CONFIG_SNAPSHOT_FILES) {
      const file = nativeConfigFile(rec, ctx, name);
      try {
        files[name] = fs.readFileSync(file, "utf8");
      } catch {
        files[name] = null;
      }
    }
    return files;
  }

  const files = {} as SnapshotFiles;
  let noPodFound = false;
  for (const name of CONFIG_SNAPSHOT_FILES) {
    try {
      files[name] = await readFileInPod(rec, k8sConfigFile(name));
    } catch (error) {
      if (isNoPodError(error)) noPodFound = true;
      files[name] = null;
    }
  }
  // No Pod means no generated files yet. Preserve an empty snapshot so a
  // first settings update is not blocked, while manual restore still fails
  // safely when it actually needs to write into a Pod.
  if (noPodFound) return { "PalWorldSettings.ini": null, "Engine.ini": null };
  return files;
}

async function writeConfigFiles(rec: InstanceRecord, ctx: DriverContext, files: SnapshotFiles): Promise<void> {
  if (rec.backend !== "k8s") {
    for (const name of CONFIG_SNAPSHOT_FILES) {
      const file = nativeConfigFile(rec, ctx, name);
      if (files[name] === null) continue;
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, files[name], "utf8");
    }
    return;
  }

  await makeDirInPod(rec, K8S_CONFIG_DIR);
  for (const name of CONFIG_SNAPSHOT_FILES) {
    try {
      if (files[name] === null) continue;
      await writeFileInPod(rec, k8sConfigFile(name), files[name]);
    } catch (error) {
      if (isNoPodError(error)) throw noPod("還原設定快照");
      throw error;
    }
  }
}

function saveSnapshot(ctx: DriverContext, rec: InstanceRecord, files: SnapshotFiles, reason: string): ConfigSnapshotInfo {
  validateSnapshotText("PalWorldSettings.ini", files["PalWorldSettings.ini"]);
  validateSnapshotText("Engine.ini", files["Engine.ini"]);
  fs.mkdirSync(configBackupsDir(ctx), { recursive: true });

  const payload: ConfigSnapshot = {
    files,
    metadata: { instanceId: rec.id, backend: rec.backend },
    reason: reason.trim() || "manual",
    createdAt: new Date().toISOString(),
    size: utf8Size(files),
  };
  for (;;) {
    const id = generatedSnapshotId();
    const file = configSnapshotPath(ctx, id);
    try {
      fs.writeFileSync(file, `${JSON.stringify(payload, null, 2)}\n`, { encoding: "utf8", flag: "wx" });
      return { id, ...payload };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EEXIST") continue;
      throw error;
    }
  }
}

export async function createConfigSnapshot(
  rec: InstanceRecord,
  ctx: DriverContext,
  reason = "manual",
): Promise<ConfigSnapshotResult> {
  const files = await readConfigFiles(rec, ctx);
  return { supported: true, snapshot: saveSnapshot(ctx, rec, files, reason) };
}

export function listConfigSnapshots(ctx: DriverContext): ConfigSnapshotList {
  if (!fs.existsSync(configBackupsDir(ctx))) return { supported: true, snapshots: [] };
  const snapshots = fs
    .readdirSync(configBackupsDir(ctx), { withFileTypes: true })
    .filter((entry) => entry.isFile() && /^([a-z0-9]+-[a-f0-9]{16})\.json$/.test(entry.name))
    .map((entry) => loadSnapshot(ctx, entry.name.slice(0, -5)))
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return { supported: true, snapshots };
}

export async function restoreConfigSnapshot(
  rec: InstanceRecord,
  ctx: DriverContext,
  id: string,
): Promise<ConfigSnapshotRestoreResult> {
  const snapshot = loadSnapshot(ctx, id);
  if (snapshot.metadata.instanceId !== rec.id) {
    throw fail("設定快照不屬於此實例", 404);
  }

  // This read happens before any target write. If k8s has no Pod it fails with
  // 409 and no local/remote config is modified.
  const safetyResult = await createConfigSnapshot(rec, ctx, `restore safety: ${id}`);
  if (!safetyResult.supported) return safetyResult;
  await writeConfigFiles(rec, ctx, snapshot.files);
  return { supported: true, snapshot, safetySnapshot: safetyResult.snapshot };
}
